---
title: "Your blog post title"
date: YYYY-MM-DD
---

author: yuyijie
email: 13588280094@163.com
description: > # this means to ignore newlines until "baseurl:"
  first time do the blog

# social links
twitter_username: I have no twitter
github_username: 13588280094@163.com

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
